name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Do not convert LF to CRLF on checkout
        run: |
          git config core.autocrlf false
          git checkout .

      - name: Build setup
        run: ./setup-build.sh
      
      - name: Build
        run: MSVC_INSTALL_DIR="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise" ./build.sh
        
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.3
        with:
          name: binary_package
          path: upload/*